### ISSUE TITLE
Implement Sonic Channel libraries for popular programming languages

### ISSUE THREAD

**Issue by valeriansaliou** [valeriansaliou/sonic#69]
Sonic cannot be integrated to an existing application code without a Sonic Channel library made for the used programming language.

Currently, a NodeJS library is available [node-sonic-channel](https://github.com/valeriansaliou/node-sonic-channel), but that's all!

We'd need to support more programming languages with clean implementations of the Sonic Channel protocol as specified in: [PROTOCOL](https://github.com/valeriansaliou/sonic/blob/master/PROTOCOL.md).

**Programming languages:**

* [x] Rust
* [x] JavaScript
* [x] Go
* [x] Java
* [x] Python
* [x] Ruby
* [x] PHP
* [ ] _(any other language?)_

**Comment by valeriansaliou** [comment]
@moshe is working on a Python binding, see #82 and https://github.com/moshe/asonic

**Comment by alexisvisco** [comment]
Hello @valeriansaliou I have implement a tiny go library https://github.com/expectedsh/go-sonic
Thanks you for your project !

**Comment by valeriansaliou** [comment]
Thank you so much, I'm adding it to the README right now.

**Comment by asonix** [comment]
Is there a Rust client library provided already? I imagine since the server is written in rust, it wouldn't be too difficult to put together a rust client.

**Comment by valeriansaliou** [comment]
Hi! Not just yet, but I am open to contributions on this :)

--

Valerian Saliou
CTO at Crisp

**Comment by kaspermeyer** [comment]
If no one else has started working on it, I’d love to take on the Ruby client!

**Comment by valeriansaliou** [comment]
@kaspermeyer I confirm that to my knowledge no one has yet started working on the Ruby client, you can go for it 😄 Thanks!

**Comment by seijikun** [comment]
Hey guys! I wrote a [small php client library](https://github.com/seijikun/php-sonic).
I am planning on using this to write a backend for Nextcloud's fulltextsearch framework.

**Comment by valeriansaliou** [comment]
@seijikun thanks! It's been added to the README in commit https://github.com/valeriansaliou/sonic/commit/777734cd3edae6b5828b1b643f021120bf9dbb02 👍

**Comment by alexisvisco** [comment]
I have implemented a bulk feature in my library, maybe the official library (in nodejs) should have it ? 
https://github.com/expectedsh/go-sonic/blob/master/sonic/ingester.go#L113

**Comment by valeriansaliou** [comment]
@alexisvisco thanks, looks neat. I'll think about it for the NodeJS library. At the network level, it's still the same so there's no (speed) optimizations involved w/ a bulk feature in the library, though it reduces the lines of code for users that need it.

**Comment by alexisvisco** [comment]
In my implementation I have splitted the number of coroutines and assign a new connection to it.

For example: 
There is an array of 10 bulk values.
I decide to split into 2 coroutines (parallelRoutines field).
There is now 2 arrays of 5 elements that will be executed in parallel. 

Each coroutines is independent so there is an optimisation (because in Go you can't read a connection with multiple routines and it's normal) because of the paralelization, you can speed up to 2 times faster in this case (if the sonic server can handle this traffic).
By the way I have executed a benchmark of this and it is positive, [look at this](https://github.com/expectedsh/go-sonic#benchmark-bulk) :smile:

**Comment by valeriansaliou** [comment]
@alexisvisco I see, you're able to increase the concurrency level at the library level. Sonic will definitely scale this better with your model, indeed. Depending on the number of cores of the machine it'll use CPU cores at their best as Sonic spawns an independent thread per Sonic Channel connection. I have a project for a worker pool for the query + suggest commands. I've already made the protocol async-compatible for search mode, so any "worker pool" improvement in Sonic will not require any change in the protocol.

**Comment by valeriansaliou** [comment]
@alexisvisco just curious, in which context / for which project are you using Sonic, if so? What motivated you to build the Golang integration?

**Comment by c-kirkeby** [comment]
I'll probably have a go at making a native Rust client. Should make for a good learning experience!

**Comment by alexisvisco** [comment]
> @alexisvisco just curious, in which context / for which project are you using Sonic, if so? What motivated you to build the Golang integration? (if that can be said publicly)

@valeriansaliou We wanted to use Sonic to ingest logs and be able to search them. However we noticed that it does not really fit because we would have wanted to be able to filter over time, and for now we can't with Sonic. We will keep an eye on sonic, for now we will rather use something else.

**Comment by atipugin** [comment]
Hi! I've created a Ruby client for Sonic - https://github.com/atipugin/sonic-ruby. There are some improvements to do, but it's already usable :)

**Comment by valeriansaliou** [comment]
Thanks @atipugin I've added it to the README 👍

**Comment by seijikun** [comment]
@touhonoob and me have merged our libraries into his repository, so you can remove my repo from the README. :smiley:

**Comment by valeriansaliou** [comment]
@seijikun done in cfbd3ac78510545c70abddd21825aa68cecd3add

**Comment by alohaking** [comment]
Hi,I found that the current java client is synchronous, so I wrote an asynchronous client using netty.[https://github.com/alohaking/jsonic](https://github.com/alohaking/jsonic)

**Comment by valeriansaliou** [comment]
@alohaking can you submit a PR where you add the link to your library in the README, below the other Java library? Thanks!

**Comment by OGKevin** [comment]
Hmm I see that im late to the party :( https://github.com/OGKevin/go-sonic

https://github.com/valeriansaliou/sonic/issues/77#issuecomment-475973778

**Comment by valeriansaliou** [comment]
You can still submit a PR to add your library to Sonic's README ;)

**Comment by FrontMage** [comment]
Hi, I made a Rust client [sonic_client](https://github.com/FrontMage/sonic_client), using `mio` and channels.
There is a question though, is `QUERY` and `SUGGEST` share the same id pool? Do I need make 2 maps for them or just one.

**Comment by valeriansaliou** [comment]
Hi there! Thanks a ton, adding it to README now!

Regarding your question, yes, they can share the same ID pool as all async events are routed on the same TCP channel (in search mode).
